services:
  postgres:
    image: postgres:17-alpine
    container_name: order-platform-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: nestjpostgres
      POSTGRES_PASSWORD: nestjpostgres
      POSTGRES_DB: order_platform

    ports:
      - 2020:5432

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
